-- FinoLens Seed Data — Nifty 50 constituents (as of April 2026)
INSERT INTO stocks (symbol, name, sector, industry, exchange, is_nifty50) VALUES
  ('ADANIENT',    'Adani Enterprises Ltd',            'Industrials',       'Diversified',                  'NSE', TRUE),
  ('ADANIPORTS',  'Adani Ports & SEZ Ltd',            'Industrials',       'Marine Ports & Services',      'NSE', TRUE),
  ('APOLLOHOSP',  'Apollo Hospitals Enterprise Ltd',  'Healthcare',        'Hospitals',                    'NSE', TRUE),
  ('ASIANPAINT',  'Asian Paints Ltd',                 'Materials',         'Paints',                       'NSE', TRUE),
  ('AXISBANK',    'Axis Bank Ltd',                    'Financials',        'Private Sector Banks',         'NSE', TRUE),
  ('BAJAJ-AUTO',  'Bajaj Auto Ltd',                   'Consumer Discretionary', 'Two & Three Wheelers',   'NSE', TRUE),
  ('BAJFINANCE',  'Bajaj Finance Ltd',                'Financials',        'Consumer Finance',             'NSE', TRUE),
  ('BAJAJFINSV',  'Bajaj Finserv Ltd',                'Financials',        'Diversified Financials',       'NSE', TRUE),
  ('BEL',         'Bharat Electronics Ltd',           'Industrials',       'Defense Electronics',          'NSE', TRUE),
  ('BPCL',        'Bharat Petroleum Corp Ltd',        'Energy',            'Oil & Gas Refining',           'NSE', TRUE),
  ('BHARTIARTL',  'Bharti Airtel Ltd',                'Communication',     'Telecom',                      'NSE', TRUE),
  ('BRITANNIA',   'Britannia Industries Ltd',         'Consumer Staples',  'Packaged Foods',               'NSE', TRUE),
  ('CIPLA',       'Cipla Ltd',                        'Healthcare',        'Pharmaceuticals',              'NSE', TRUE),
  ('COALINDIA',   'Coal India Ltd',                   'Energy',            'Coal & Consumable Fuels',      'NSE', TRUE),
  ('DRREDDY',     'Dr. Reddy''s Laboratories Ltd',    'Healthcare',        'Pharmaceuticals',              'NSE', TRUE),
  ('EICHERMOT',   'Eicher Motors Ltd',                'Consumer Discretionary', 'Automobiles',            'NSE', TRUE),
  ('ETERNAL',     'Eternal Ltd',                      'Consumer Discretionary', 'Food Delivery',           'NSE', TRUE),
  ('GRASIM',      'Grasim Industries Ltd',            'Materials',         'Diversified Chemicals',        'NSE', TRUE),
  ('HCLTECH',     'HCL Technologies Ltd',             'Information Technology', 'IT Services',            'NSE', TRUE),
  ('HDFCBANK',    'HDFC Bank Ltd',                    'Financials',        'Private Sector Banks',         'NSE', TRUE),
  ('HDFCLIFE',    'HDFC Life Insurance Co Ltd',       'Financials',        'Life Insurance',               'NSE', TRUE),
  ('HEROMOTOCO',  'Hero MotoCorp Ltd',                'Consumer Discretionary', 'Two & Three Wheelers',   'NSE', TRUE),
  ('HINDALCO',    'Hindalco Industries Ltd',          'Materials',         'Aluminium',                    'NSE', TRUE),
  ('HINDUNILVR',  'Hindustan Unilever Ltd',           'Consumer Staples',  'Personal Products',            'NSE', TRUE),
  ('ICICIBANK',   'ICICI Bank Ltd',                   'Financials',        'Private Sector Banks',         'NSE', TRUE),
  ('ITC',         'ITC Ltd',                          'Consumer Staples',  'Tobacco',                      'NSE', TRUE),
  ('INDUSINDBK',  'IndusInd Bank Ltd',                'Financials',        'Private Sector Banks',         'NSE', TRUE),
  ('INFY',        'Infosys Ltd',                      'Information Technology', 'IT Services',            'NSE', TRUE),
  ('JSWSTEEL',    'JSW Steel Ltd',                    'Materials',         'Steel',                        'NSE', TRUE),
  ('KOTAKBANK',   'Kotak Mahindra Bank Ltd',          'Financials',        'Private Sector Banks',         'NSE', TRUE),
  ('LT',          'Larsen & Toubro Ltd',              'Industrials',       'Construction & Engineering',   'NSE', TRUE),
  ('LICI',        'Life Insurance Corporation of India', 'Financials',     'Life Insurance',               'NSE', TRUE),
  ('M&M',         'Mahindra & Mahindra Ltd',          'Consumer Discretionary', 'Automobiles',            'NSE', TRUE),
  ('MARUTI',      'Maruti Suzuki India Ltd',          'Consumer Discretionary', 'Automobiles',            'NSE', TRUE),
  ('NESTLEIND',   'Nestle India Ltd',                 'Consumer Staples',  'Packaged Foods',               'NSE', TRUE),
  ('NTPC',        'NTPC Ltd',                         'Utilities',         'Electric Utilities',           'NSE', TRUE),
  ('ONGC',        'Oil & Natural Gas Corp Ltd',       'Energy',            'Oil & Gas Exploration',        'NSE', TRUE),
  ('POWERGRID',   'Power Grid Corp of India Ltd',     'Utilities',         'Electric Utilities',           'NSE', TRUE),
  ('RELIANCE',    'Reliance Industries Ltd',          'Energy',            'Oil Gas & Consumable Fuels',   'NSE', TRUE),
  ('SBILIFE',     'SBI Life Insurance Co Ltd',        'Financials',        'Life Insurance',               'NSE', TRUE),
  ('SHRIRAMFIN',  'Shriram Finance Ltd',              'Financials',        'Consumer Finance',             'NSE', TRUE),
  ('SBIN',        'State Bank of India',              'Financials',        'Public Sector Banks',          'NSE', TRUE),
  ('SUNPHARMA',   'Sun Pharmaceutical Industries Ltd','Healthcare',        'Pharmaceuticals',              'NSE', TRUE),
  ('TCS',         'Tata Consultancy Services Ltd',    'Information Technology', 'IT Services',            'NSE', TRUE),
  ('TATACONSUM',  'Tata Consumer Products Ltd',       'Consumer Staples',  'Packaged Foods',               'NSE', TRUE),
  ('TATAMOTORS',  'Tata Motors Ltd',                  'Consumer Discretionary', 'Automobiles',            'NSE', TRUE),
  ('TATASTEEL',   'Tata Steel Ltd',                   'Materials',         'Steel',                        'NSE', TRUE),
  ('TECHM',       'Tech Mahindra Ltd',                'Information Technology', 'IT Services',            'NSE', TRUE),
  ('TITAN',       'Titan Company Ltd',                'Consumer Discretionary', 'Luxury Goods',           'NSE', TRUE),
  ('TRENT',       'Trent Ltd',                        'Consumer Discretionary', 'Apparel Retail',         'NSE', TRUE),
  ('ULTRACEMCO',  'UltraTech Cement Ltd',             'Materials',         'Construction Materials',       'NSE', TRUE),
  ('WIPRO',       'Wipro Ltd',                        'Information Technology', 'IT Services',            'NSE', TRUE)
ON CONFLICT (symbol) DO UPDATE SET
    name       = EXCLUDED.name,
    sector     = EXCLUDED.sector,
    industry   = EXCLUDED.industry,
    is_nifty50 = EXCLUDED.is_nifty50,
    updated_at = NOW();
